on:
  # - schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '0 */12 * * *'
  workflow_dispatch:

jobs:
  changelog:
    strategy:
      matrix:
        branch: [main, dev]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch ${{ matrix.branch }}
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0
      - name: "Check for new commits"
        run: |
          BRANCH=$(git branch --show-current)
          LAST_TAG="$(git describe --abbrev=0 || echo "-1")"
          echo "Last generated tag -> $LAST_TAG"
          COMMIT_COUNT=0
          if [ "$LAST_TAG" == "-1" ]; then
              COMMIT_COUNT=$(git log --oneline | wc -l)
          else
              COMMIT_COUNT=$(git rev-list $LAST_TAG..HEAD --count)
          fi

          if [ $COMMIT_COUNT -gt 0 ]; then
            echo "Branch $BRANCH have $COMMIT_COUNT new commits"
          else 
            echo "Branch $BRANCH don't have new commits"
          fi
